/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hanfei' at '17-2-22 下午3:50' with Gradle 2.14.1
 *
 * @author hanfei, @date 17-2-22 下午3:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
